import { parseJsonObject, parseJsonString, type ParseResult } from "./common.js";

export const GIT_ERROR_CODES = ["git_invalid_request", "git_not_repository", "git_not_found", "git_conflict", "git_unauthorized", "git_forbidden", "git_unavailable", "git_internal_error"] as const;
export type GitErrorCode = (typeof GIT_ERROR_CODES)[number];
export type GitErrorResponse = { error: string; code: GitErrorCode };
export const gitError = (code: GitErrorCode): GitErrorResponse => ({ error: code === "git_invalid_request" ? "Invalid git request" : "Git operation failed", code });

export type GitStatusFile = { path: string; index: string; working_dir: string };
export type GitMergeInProgress = { head: string; message: string };
export type GitRebaseInProgress = { headName: string; onto: string };
export type GitAttentionReason = "merge" | "rebase" | "cherry-pick" | "revert" | "bisect" | null;
export type GitStatusResponse = { isGitRepository?: boolean; branch?: string | null; current: string | null; tracking: string | null; ahead: number; behind: number; files: GitStatusFile[]; isClean: boolean; diffStats?: Record<string, GitDiffStat>; mergeInProgress: GitMergeInProgress | null; rebaseInProgress: GitRebaseInProgress | null; attentionReason?: GitAttentionReason };
export type GitDiffStat = { insertions: number; deletions: number };
export type GitDirectoryQuery = { directory: string };
export type GitRemoteUrlQuery = GitDirectoryQuery & { remote?: string };
export type GitStatusQuery = GitDirectoryQuery & { mode?: "light" };
export type GitDiffRequest = { path: string; staged?: boolean; contextLines?: number };
export type GitDiffResponse = { diff: string };
export type GitFileDiffRequest = { path: string; staged?: boolean };
export type GitFileDiffResponse = { original: string; modified: string; path: string; isBinary: boolean };
export type GitSuccessResponse = { success: boolean };
export type GitRepositoryCheckResponse = { isGitRepository: boolean };
export type GitLocalIdentityResponse = { hasLocalIdentity: boolean };
export type GitLinkedWorktreeResponse = { linked: boolean };
export type GitBatchCheckRequest = { directories: string[] };
export type GitBatchCheckResponse = { results: Record<string, boolean> };
export type GitBranchDetails = { current: boolean; name: string; commit: string; label: string; tracking?: string; ahead?: number; behind?: number };
export type GitBranchResponse = { all: string[]; current: string | null; branches: Record<string, GitBranchDetails> };
export type GitBranchMutationRequest = { branch?: string; name?: string; startPoint?: string; oldName?: string; newName?: string; force?: boolean; remote?: string };
export type GitBranchMutationResponse = GitSuccessResponse & { branch: string };
export type GitDeleteBranchRequest = { branch: string; force?: boolean };
export type GitDeleteRemoteBranchRequest = { branch: string; remote?: string };
export type GitRemoveRemoteRequest = { remote: string };
export type GitCommitRequest = { message: string; addAll?: boolean; files?: string[] };
export type GitCommitSummary = { changes: number; insertions: number; deletions: number };
export type GitCommitResponse = GitSuccessResponse & { commit: string; branch: string; summary: GitCommitSummary };
export type GitCommitFile = { path: string; insertions: number; deletions: number; isBinary: boolean; changeType: string };
export type GitCommitFilesResponse = { files: GitCommitFile[] };
export type GitCommitFilesQuery = GitDirectoryQuery & { hash: string };
export type GitPushRequest = { remote?: string; branch?: string; options?: string[] | Record<string, unknown> };
export type GitPushResponse = GitSuccessResponse & { pushed: Array<{ local: string; remote: string }>; repo: string; ref: unknown };
export type GitPullRequest = { remote?: string; branch?: string; options?: Record<string, unknown> };
export type GitPullResponse = GitSuccessResponse & { summary: GitCommitSummary; files: string[]; insertions: number; deletions: number };
export type GitFetchRequest = { remote?: string; branch?: string; options?: Record<string, unknown> };
export type GitRebaseRequest = { onto: string };
export type GitMergeRequest = { branch: string };
export type GitStashRequest = { message?: string; includeUntracked?: boolean };
export type GitRemote = { name: string; fetchUrl: string; pushUrl: string };
export type GitRemoteUrlResponse = { url: string | null };
export type GitLogEntry = { hash: string; date: string; message: string; refs: string; body: string; author_name: string; author_email: string; filesChanged: number; insertions: number; deletions: number };
export type GitLogResponse = { all: GitLogEntry[]; latest: GitLogEntry | null; total: number };
export type GitLogQuery = GitDirectoryQuery & { maxCount?: number; from?: string; to?: string; file?: string };
export type GitIdentityAuthType = "ssh" | "token";
export type GitIdentityProfile = { id: string; name: string; userName: string; userEmail: string; authType?: GitIdentityAuthType; sshKey?: string | null; host?: string | null; color?: string | null; icon?: string | null };
export type GitIdentitySummary = { userName: string | null; userEmail: string | null; sshCommand: string | null };
export type GitIdentitySetRequest = { profileId: string };
export type GitIdentitySetResponse = GitSuccessResponse & { profile: GitIdentityProfile };
export type GitCredentialEntry = { host: string; username: string };
export type GitGeneratedCommitMessage = { subject: string; highlights: string[] };
export type GitGeneratedPullRequestDescription = { title: string; body: string };
export type GitWorktreeInfo = { head: string; name: string; branch: string; path: string };
export type GitWorktreeCreateRequest = { mode?: "new" | "existing"; worktreeName?: string; name?: string; branchName?: string; startRef?: string; existingBranch?: string; setUpstream?: boolean; upstreamRemote?: string; upstreamBranch?: string; ensureRemoteName?: string; ensureRemoteUrl?: string; startCommand?: string };
export type GitWorktreeValidationResult = { ok: boolean; errors: Array<{ code: string; message: string }>; resolved: { mode: "new" | "existing"; localBranch: string | null } };
export type GitWorktreeBootstrapStatus = { status: "pending" | "ready" | "failed"; error: string | null; updatedAt: number };
export type GitWorktreeRemoveRequest = { directory: string; deleteLocalBranch?: boolean };
export type GitWorktreeDirectoryRequest = { directory: string; worktreeRoot: string };
export type GitWorktreeDirectoryResult = { valid: boolean; insideWorktreeRoot: boolean; resolvedWorktreeRoot: string | null; resolvedCwd: string | null };
export type GitConflictDetails = { statusPorcelain: string; unmergedFiles: string[]; diff: string; headInfo: string; operation: string };
export type GitOperationResponse = GitSuccessResponse & { conflict?: boolean; conflictFiles?: string[] };
export type GitCanonicalizeWorktreeResponse = { worktreeRoot: string | null; cwd: string | null; branch: string | null; headState: "branch" | "detached" | "unborn"; worktreeStatus: "ready" | "missing" | "invalid" | "not-a-repo"; legacy: boolean; degraded: boolean; attentionReason?: GitAttentionReason };

const invalid = <T = never>(error: string): ParseResult<T> => ({ ok: false, error });
const object = (value: unknown): Record<string, unknown> | null => { const result = parseJsonObject(value); return result.ok ? result.value : null; };
const string = (value: unknown): value is string => typeof value === "string";
const required = (value: unknown, name: string): ParseResult<string> => { const result = parseJsonString(value); return result.ok && result.value.trim() ? { ok: true, value: result.value.trim() } : invalid(`${name} is required`); };
const nullableString = (value: unknown): value is string | null => value === null || string(value);
const optionalString = (value: unknown): value is string | undefined => value === undefined || string(value);
const optionalBoolean = (value: unknown): value is boolean | undefined => value === undefined || typeof value === "boolean";
const strings = (value: unknown): value is string[] => Array.isArray(value) && value.every(string);
const optionalObject = (value: unknown): value is Record<string, unknown> | undefined => value === undefined || object(value) !== null;
const isEmptyRequest = (value: unknown) => value === undefined || object(value) !== null;

export function parseGitDirectoryQuery(value: unknown): ParseResult<GitDirectoryQuery> { const input = object(value); const directory = input && required(input.directory, "directory"); return directory?.ok ? { ok: true, value: { directory: directory.value } } : invalid("invalid git directory query"); }
export function parseGitRemoteUrlQuery(value: unknown): ParseResult<GitRemoteUrlQuery> { const base = parseGitDirectoryQuery(value); const input = object(value); return base.ok && input && optionalString(input.remote) && (input.remote === undefined || input.remote.trim()) ? { ok: true, value: { ...base.value, ...(input.remote === undefined ? {} : { remote: input.remote.trim() }) } } : invalid("invalid git remote url query"); }
export function parseGitStatusQuery(value: unknown): ParseResult<GitStatusQuery> { const base = parseGitDirectoryQuery(value); const input = object(value); return base.ok && input && (input.mode === undefined || input.mode === "light") ? { ok: true, value: { ...base.value, ...(input.mode === "light" ? { mode: "light" as const } : {}) } } : invalid("invalid git status query"); }
export function parseGitDiffRequest(value: unknown): ParseResult<GitDiffRequest> { const input = object(value); const path = input && required(input.path, "path"); return input && path?.ok && optionalBoolean(input.staged) && (input.contextLines === undefined || (typeof input.contextLines === "number" && Number.isFinite(input.contextLines))) ? { ok: true, value: input as GitDiffRequest } : invalid("invalid git diff request"); }
export function parseGitFileDiffRequest(value: unknown): ParseResult<GitFileDiffRequest> { const input = object(value); const path = input && required(input.path, "path"); return input && path?.ok && optionalBoolean(input.staged) ? { ok: true, value: input as GitFileDiffRequest } : invalid("invalid git file diff request"); }
export function parseGitBatchCheckRequest(value: unknown): ParseResult<GitBatchCheckRequest> { const input = object(value); return input && strings(input.directories) && input.directories.length > 0 && input.directories.length <= 50 && input.directories.every((item) => item.trim()) ? { ok: true, value: { directories: input.directories.map((item) => item.trim()) } } : invalid("invalid git batch request"); }
export function parseGitBranchMutationRequest(value: unknown): ParseResult<GitBranchMutationRequest> { const input = object(value); if (!input || !["branch", "name", "startPoint", "oldName", "newName", "remote"].every((key) => optionalString(input[key])) || !optionalBoolean(input.force)) return invalid("invalid git branch request"); const names = [input.branch, input.name, input.oldName, input.newName].filter((item) => item !== undefined); return names.every((item) => typeof item === "string" && item.trim()) ? { ok: true, value: input as GitBranchMutationRequest } : invalid("invalid git branch request"); }
export function parseGitDeleteBranchRequest(value: unknown): ParseResult<GitDeleteBranchRequest> { const result = parseGitBranchMutationRequest(value); return result.ok && typeof result.value.branch === "string" ? { ok: true, value: result.value as GitDeleteBranchRequest } : invalid("invalid git delete branch request"); }
export function parseGitCreateBranchRequest(value: unknown): ParseResult<Pick<GitBranchMutationRequest, "name" | "startPoint">> { const input = object(value); const name = input && required(input.name, "name"); return input && name?.ok && optionalString(input.startPoint) ? { ok: true, value: { name: name.value, ...(input.startPoint === undefined ? {} : { startPoint: input.startPoint }) } } : invalid("invalid git create branch request"); }
export function parseGitRenameBranchRequest(value: unknown): ParseResult<Pick<GitBranchMutationRequest, "oldName" | "newName">> { const input = object(value); const oldName = input && required(input.oldName, "oldName"); const newName = input && required(input.newName, "newName"); return oldName?.ok && newName?.ok ? { ok: true, value: { oldName: oldName.value, newName: newName.value } } : invalid("invalid git rename branch request"); }
export function parseGitCheckoutBranchRequest(value: unknown): ParseResult<Pick<GitBranchMutationRequest, "branch">> { const input = object(value); const branch = input && required(input.branch, "branch"); return branch?.ok ? { ok: true, value: { branch: branch.value } } : invalid("invalid git checkout branch request"); }
export function parseGitDeleteRemoteBranchRequest(value: unknown): ParseResult<GitDeleteRemoteBranchRequest> { const input = object(value); const branch = input && required(input.branch, "branch"); return input && branch?.ok && optionalString(input.remote) ? { ok: true, value: input as GitDeleteRemoteBranchRequest } : invalid("invalid git remote branch request"); }
export function parseGitRemoveRemoteRequest(value: unknown): ParseResult<GitRemoveRemoteRequest> { const input = object(value); const remote = input && required(input.remote, "remote"); return remote?.ok ? { ok: true, value: { remote: remote.value } } : invalid("invalid git remove remote request"); }
export function parseGitCommitRequest(value: unknown): ParseResult<GitCommitRequest> { const input = object(value); const message = input && required(input.message, "message"); return input && message?.ok && optionalBoolean(input.addAll) && (input.files === undefined || strings(input.files)) ? { ok: true, value: input as GitCommitRequest } : invalid("invalid git commit request"); }
const remoteRequest = <T>(value: unknown, label: string): ParseResult<T> => { const input = object(value); return input && optionalString(input.remote) && optionalString(input.branch) && optionalObject(input.options) && (!Array.isArray(input.options) || strings(input.options)) ? { ok: true, value: input as T } : invalid(`invalid git ${label} request`); };
export const parseGitPushRequest = (value: unknown) => remoteRequest<GitPushRequest>(value, "push");
export const parseGitPullRequest = (value: unknown) => remoteRequest<GitPullRequest>(value, "pull");
export const parseGitFetchRequest = (value: unknown) => remoteRequest<GitFetchRequest>(value, "fetch");
export function parseGitRebaseRequest(value: unknown): ParseResult<GitRebaseRequest> { const input = object(value); const onto = input && required(input.onto, "onto"); return onto?.ok ? { ok: true, value: { onto: onto.value } } : invalid("invalid git rebase request"); }
export function parseGitMergeRequest(value: unknown): ParseResult<GitMergeRequest> { const input = object(value); const branch = input && required(input.branch, "branch"); return branch?.ok ? { ok: true, value: { branch: branch.value } } : invalid("invalid git merge request"); }
export function parseGitStashRequest(value: unknown): ParseResult<GitStashRequest> { const input = object(value); return input && optionalString(input.message) && optionalBoolean(input.includeUntracked) ? { ok: true, value: input as GitStashRequest } : invalid("invalid git stash request"); }
export function parseGitLogQuery(value: unknown): ParseResult<GitLogQuery> { const base = parseGitDirectoryQuery(value); const input = object(value); return base.ok && input && optionalString(input.from) && optionalString(input.to) && optionalString(input.file) && (input.maxCount === undefined || typeof input.maxCount === "number") ? { ok: true, value: { ...base.value, ...input } as GitLogQuery } : invalid("invalid git log query"); }
export function parseGitCommitFilesQuery(value: unknown): ParseResult<GitCommitFilesQuery> { const base = parseGitDirectoryQuery(value); const input = object(value); const hash = input && required(input.hash, "hash"); return base.ok && hash?.ok ? { ok: true, value: { ...base.value, hash: hash.value } } : invalid("invalid git commit files query"); }
export function parseGitIdentityProfile(value: unknown): ParseResult<GitIdentityProfile> { const input = object(value); return input && ["id", "name", "userName", "userEmail"].every((key) => string(input[key]) && input[key].trim()) && (input.authType === undefined || input.authType === "ssh" || input.authType === "token") && ["sshKey", "host", "color", "icon"].every((key) => input[key] === undefined || nullableString(input[key])) ? { ok: true, value: input as GitIdentityProfile } : invalid("invalid git identity profile"); }
export function parseGitIdentitySetRequest(value: unknown): ParseResult<GitIdentitySetRequest> { const input = object(value); const profileId = input && required(input.profileId, "profileId"); return profileId?.ok ? { ok: true, value: { profileId: profileId.value } } : invalid("invalid git identity request"); }
export function parseGitWorktreeCreateRequest(value: unknown): ParseResult<GitWorktreeCreateRequest> { const input = object(value); return input && (input.mode === undefined || input.mode === "new" || input.mode === "existing") && ["worktreeName", "name", "branchName", "startRef", "existingBranch", "upstreamRemote", "upstreamBranch", "ensureRemoteName", "ensureRemoteUrl", "startCommand"].every((key) => optionalString(input[key])) && optionalBoolean(input.setUpstream) ? { ok: true, value: input as GitWorktreeCreateRequest } : invalid("invalid git worktree request"); }
export function parseGitWorktreeRemoveRequest(value: unknown): ParseResult<GitWorktreeRemoveRequest> { const input = object(value); const directory = input && required(input.directory, "directory"); return input && directory?.ok && optionalBoolean(input.deleteLocalBranch) ? { ok: true, value: input as GitWorktreeRemoveRequest } : invalid("invalid git worktree remove request"); }
export function parseGitWorktreeDirectoryRequest(value: unknown): ParseResult<GitWorktreeDirectoryRequest> { const input = object(value); const directory = input && required(input.directory, "directory"); const root = input && required(input.worktreeRoot, "worktreeRoot"); return directory?.ok && root?.ok ? { ok: true, value: { directory: directory.value, worktreeRoot: root.value } } : invalid("invalid git worktree directory request"); }
export const parseGitCanonicalizeWorktreeRequest = parseGitDirectoryQuery;
export const parseGitEmptyRequest = (value: unknown): ParseResult<Record<string, never>> => isEmptyRequest(value) ? { ok: true, value: {} } : invalid("invalid empty git request");

const isStatusEnvelope = (input: Record<string, unknown>) => [nullableString(input.current), nullableString(input.tracking), typeof input.ahead === "number", typeof input.behind === "number", Array.isArray(input.files), typeof input.isClean === "boolean", nullableObject(input.mergeInProgress, ["head", "message"]), nullableObject(input.rebaseInProgress, ["headName", "onto"]), attention(input.attentionReason)].every(Boolean);
const isStatusFile = (item: unknown) => { const file = object(item); return file !== null && ["path", "index", "working_dir"].every((key) => string(file[key])); };
export function parseGitStatusResponse(value: unknown): ParseResult<GitStatusResponse> { const input = object(value); if (!input || !isStatusEnvelope(input) || !Array.isArray(input.files) || !input.files.every(isStatusFile) || (input.diffStats !== undefined && !parseDiffStats(input.diffStats))) return invalid("invalid git status response"); return { ok: true, value: input as GitStatusResponse }; }
const nullableObject = (value: unknown, fields: string[]) => value === null || (object(value) !== null && fields.every((field) => string(object(value)![field])));
const attention = (value: unknown) => value === undefined || value === null || ["merge", "rebase", "cherry-pick", "revert", "bisect"].includes(value as string);
const parseDiffStats = (value: unknown) => { const input = object(value); return input !== null && Object.values(input).every((entry) => { const stat = object(entry); return stat && typeof stat.insertions === "number" && typeof stat.deletions === "number"; }); };
export function parseGitDiffResponse(value: unknown): ParseResult<GitDiffResponse> { const input = object(value); return input && string(input.diff) ? { ok: true, value: input as GitDiffResponse } : invalid("invalid git diff response"); }
export function parseGitFileDiffResponse(value: unknown): ParseResult<GitFileDiffResponse> { const input = object(value); return input && ["original", "modified", "path"].every((key) => string(input[key])) && typeof input.isBinary === "boolean" ? { ok: true, value: input as GitFileDiffResponse } : invalid("invalid git file diff response"); }
export function parseGitSuccessResponse(value: unknown): ParseResult<GitSuccessResponse> { const input = object(value); return input && typeof input.success === "boolean" ? { ok: true, value: input as GitSuccessResponse } : invalid("invalid git success response"); }
export function parseGitRepositoryCheckResponse(value: unknown): ParseResult<GitRepositoryCheckResponse> { const input = object(value); return input && typeof input.isGitRepository === "boolean" ? { ok: true, value: input as GitRepositoryCheckResponse } : invalid("invalid git repository response"); }
export function parseGitLocalIdentityResponse(value: unknown): ParseResult<GitLocalIdentityResponse> { const input = object(value); return input && typeof input.hasLocalIdentity === "boolean" ? { ok: true, value: input as GitLocalIdentityResponse } : invalid("invalid git local identity response"); }
export function parseGitLinkedWorktreeResponse(value: unknown): ParseResult<GitLinkedWorktreeResponse> { const input = object(value); return input && typeof input.linked === "boolean" ? { ok: true, value: input as GitLinkedWorktreeResponse } : invalid("invalid git worktree type response"); }
export function parseGitBatchCheckResponse(value: unknown): ParseResult<GitBatchCheckResponse> { const input = object(value); const results = input && object(input.results); return results && Object.values(results).every((entry) => typeof entry === "boolean") ? { ok: true, value: { results: results as Record<string, boolean> } } : invalid("invalid git batch response"); }
export function parseGitBranchResponse(value: unknown): ParseResult<GitBranchResponse> { const input = object(value); const branches = input && object(input.branches); if (!input || !strings(input.all) || !nullableString(input.current) || !branches) return invalid("invalid git branches response"); return Object.values(branches).every((entry) => { const branch = object(entry); return branch && typeof branch.current === "boolean" && ["name", "commit", "label"].every((key) => string(branch[key])) && optionalString(branch.tracking) && (branch.ahead === undefined || typeof branch.ahead === "number") && (branch.behind === undefined || typeof branch.behind === "number"); }) ? { ok: true, value: input as GitBranchResponse } : invalid("invalid git branches response"); }
export function parseGitBranchMutationResponse(value: unknown): ParseResult<GitBranchMutationResponse> { const input = object(value); return input && typeof input.success === "boolean" && string(input.branch) ? { ok: true, value: input as GitBranchMutationResponse } : invalid("invalid git branch response"); }
const summary = (value: unknown): value is GitCommitSummary => { const input = object(value); return !!input && ["changes", "insertions", "deletions"].every((key) => typeof input[key] === "number"); };
export function parseGitCommitResponse(value: unknown): ParseResult<GitCommitResponse> { const input = object(value); return input && typeof input.success === "boolean" && string(input.commit) && string(input.branch) && summary(input.summary) ? { ok: true, value: input as GitCommitResponse } : invalid("invalid git commit response"); }
export function parseGitCommitFilesResponse(value: unknown): ParseResult<GitCommitFilesResponse> { const input = object(value); return input && Array.isArray(input.files) && input.files.every((entry) => { const file = object(entry); return file && string(file.path) && typeof file.insertions === "number" && typeof file.deletions === "number" && typeof file.isBinary === "boolean" && string(file.changeType); }) ? { ok: true, value: input as GitCommitFilesResponse } : invalid("invalid git commit files response"); }
export function parseGitPushResponse(value: unknown): ParseResult<GitPushResponse> { const input = object(value); return input && typeof input.success === "boolean" && Array.isArray(input.pushed) && input.pushed.every((entry) => { const push = object(entry); return push && string(push.local) && string(push.remote); }) && string(input.repo) && "ref" in input ? { ok: true, value: input as GitPushResponse } : invalid("invalid git push response"); }
export function parseGitPullResponse(value: unknown): ParseResult<GitPullResponse> { const input = object(value); return input && typeof input.success === "boolean" && summary(input.summary) && strings(input.files) && typeof input.insertions === "number" && typeof input.deletions === "number" ? { ok: true, value: input as GitPullResponse } : invalid("invalid git pull response"); }
export function parseGitRemotesResponse(value: unknown): ParseResult<GitRemote[]> { return Array.isArray(value) && value.every((entry) => { const remote = object(entry); return remote && ["name", "fetchUrl", "pushUrl"].every((key) => string(remote[key])); }) ? { ok: true, value: value as GitRemote[] } : invalid("invalid git remotes response"); }
export function parseGitLogResponse(value: unknown): ParseResult<GitLogResponse> { const input = object(value); const entry = (item: unknown) => { const log = object(item); return log && ["hash", "date", "message", "refs", "body", "author_name", "author_email"].every((key) => string(log[key])) && ["filesChanged", "insertions", "deletions"].every((key) => typeof log[key] === "number"); }; return input && Array.isArray(input.all) && input.all.every(entry) && (input.latest === null || entry(input.latest)) && typeof input.total === "number" ? { ok: true, value: input as GitLogResponse } : invalid("invalid git log response"); }
export function parseGitIdentitySummary(value: unknown): ParseResult<GitIdentitySummary> { const input = object(value); return input && ["userName", "userEmail", "sshCommand"].every((key) => nullableString(input[key])) ? { ok: true, value: input as GitIdentitySummary } : invalid("invalid git identity response"); }
export function parseGitIdentityProfilesResponse(value: unknown): ParseResult<GitIdentityProfile[]> { if (!Array.isArray(value)) return invalid("invalid git identities response"); const profiles = value.map(parseGitIdentityProfile); return profiles.every((result) => result.ok) ? { ok: true, value: profiles.map((result) => (result as { ok: true; value: GitIdentityProfile }).value) } : invalid("invalid git identities response"); }
export const parseGitIdentityProfileResponse = parseGitIdentityProfile;
export function parseGitIdentitySetResponse(value: unknown): ParseResult<GitIdentitySetResponse> { const input = object(value); const profile = input && parseGitIdentityProfile(input.profile); return input && typeof input.success === "boolean" && profile?.ok ? { ok: true, value: input as GitIdentitySetResponse } : invalid("invalid git identity set response"); }
export function parseGitCredentialsResponse(value: unknown): ParseResult<GitCredentialEntry[]> { return Array.isArray(value) && value.every((entry) => { const credential = object(entry); return credential && string(credential.host) && string(credential.username); }) ? { ok: true, value: value as GitCredentialEntry[] } : invalid("invalid git credentials response"); }
export function parseGitGeneratedCommitMessageResponse(value: unknown): ParseResult<{ message: GitGeneratedCommitMessage }> { const input = object(value); const message = input && object(input.message); return message && string(message.subject) && strings(message.highlights) ? { ok: true, value: { message: { subject: message.subject, highlights: message.highlights } } } : invalid("invalid git commit generation response"); }
export function parseGitGeneratedPullRequestDescriptionResponse(value: unknown): ParseResult<GitGeneratedPullRequestDescription> { const input = object(value); return input && string(input.title) && string(input.body) ? { ok: true, value: { title: input.title, body: input.body } } : invalid("invalid git pull request generation response"); }
export function parseGitWorktreesResponse(value: unknown): ParseResult<GitWorktreeInfo[]> { return Array.isArray(value) && value.every((entry) => { const worktree = object(entry); return worktree && ["head", "name", "branch", "path"].every((key) => string(worktree[key])); }) ? { ok: true, value: value as GitWorktreeInfo[] } : invalid("invalid git worktrees response"); }
export const parseGitWorktreeCreateResponse = (value: unknown) => { const parsed = parseGitWorktreesResponse([value]); return parsed.ok ? { ok: true as const, value: parsed.value[0] } : parsed; };
export function parseGitWorktreeValidationResult(value: unknown): ParseResult<GitWorktreeValidationResult> { const input = object(value); const resolved = input && object(input.resolved); return input && typeof input.ok === "boolean" && Array.isArray(input.errors) && input.errors.every((entry) => { const error = object(entry); return error && string(error.code) && string(error.message); }) && resolved && (resolved.mode === "new" || resolved.mode === "existing") && nullableString(resolved.localBranch) ? { ok: true, value: input as GitWorktreeValidationResult } : invalid("invalid git worktree validation response"); }
export function parseGitWorktreeBootstrapStatus(value: unknown): ParseResult<GitWorktreeBootstrapStatus> { const input = object(value); return input && ["pending", "ready", "failed"].includes(input.status as string) && nullableString(input.error) && typeof input.updatedAt === "number" ? { ok: true, value: input as GitWorktreeBootstrapStatus } : invalid("invalid git worktree bootstrap response"); }
export function parseGitWorktreeDirectoryResult(value: unknown): ParseResult<GitWorktreeDirectoryResult> { const input = object(value); return input && typeof input.valid === "boolean" && typeof input.insideWorktreeRoot === "boolean" && nullableString(input.resolvedWorktreeRoot) && nullableString(input.resolvedCwd) ? { ok: true, value: input as GitWorktreeDirectoryResult } : invalid("invalid git worktree directory response"); }
export function parseGitConflictDetails(value: unknown): ParseResult<GitConflictDetails> { const input = object(value); return input && ["statusPorcelain", "diff", "headInfo", "operation"].every((key) => string(input[key])) && strings(input.unmergedFiles) ? { ok: true, value: input as GitConflictDetails } : invalid("invalid git conflict response"); }
export function parseGitOperationResponse(value: unknown): ParseResult<GitOperationResponse> { const input = object(value); return input && typeof input.success === "boolean" && optionalBoolean(input.conflict) && (input.conflictFiles === undefined || strings(input.conflictFiles)) ? { ok: true, value: input as GitOperationResponse } : invalid("invalid git operation response"); }
export function parseGitCanonicalizeWorktreeResponse(value: unknown): ParseResult<GitCanonicalizeWorktreeResponse> { const input = object(value); return input && ["worktreeRoot", "cwd", "branch"].every((key) => nullableString(input[key])) && ["branch", "detached", "unborn"].includes(input.headState as string) && ["ready", "missing", "invalid", "not-a-repo"].includes(input.worktreeStatus as string) && typeof input.legacy === "boolean" && typeof input.degraded === "boolean" && attention(input.attentionReason) ? { ok: true, value: input as GitCanonicalizeWorktreeResponse } : invalid("invalid git canonicalize response"); }
export function parseGitRemoteUrlResponse(value: unknown): ParseResult<GitRemoteUrlResponse> { const input = object(value); return input && nullableString(input.url) ? { ok: true, value: input as GitRemoteUrlResponse } : invalid("invalid git remote url response"); }
export function parseGitErrorResponse(value: unknown): ParseResult<GitErrorResponse> { const input = object(value); return input && string(input.error) && typeof input.code === "string" && (GIT_ERROR_CODES as readonly string[]).includes(input.code) ? { ok: true, value: input as GitErrorResponse } : invalid("invalid git error response"); }

type RouteParser = (value: unknown) => ParseResult<unknown>;
const response = (parser: RouteParser) => parser;
export const GIT_ROUTE_CONTRACTS: Record<string, { request: RouteParser; response: RouteParser }> = {
  "GET /api/git/identities": { request: parseGitEmptyRequest, response: response(parseGitIdentityProfilesResponse) }, "POST /api/git/identities": { request: parseGitIdentityProfile, response: response(parseGitIdentityProfileResponse) }, "PUT /api/git/identities/:id": { request: parseGitIdentityProfile, response: response(parseGitIdentityProfileResponse) }, "DELETE /api/git/identities/:id": { request: parseGitEmptyRequest, response: response(parseGitSuccessResponse) },
  "GET /api/git/global-identity": { request: parseGitEmptyRequest, response: response(parseGitIdentitySummary) }, "GET /api/git/discover-credentials": { request: parseGitEmptyRequest, response: response(parseGitCredentialsResponse) }, "GET /api/git/check": { request: parseGitDirectoryQuery, response: response(parseGitRepositoryCheckResponse) }, "POST /api/git/check-batch": { request: parseGitBatchCheckRequest, response: response(parseGitBatchCheckResponse) }, "GET /api/git/remote-url": { request: parseGitRemoteUrlQuery, response: response(parseGitRemoteUrlResponse) }, "GET /api/git/current-identity": { request: parseGitDirectoryQuery, response: response(parseGitIdentitySummary) }, "GET /api/git/has-local-identity": { request: parseGitDirectoryQuery, response: response(parseGitLocalIdentityResponse) }, "POST /api/git/set-identity": { request: parseGitIdentitySetRequest, response: response(parseGitIdentitySetResponse) },
  "GET /api/git/status": { request: parseGitStatusQuery, response: response(parseGitStatusResponse) }, "GET /api/git/diff": { request: parseGitDiffRequest, response: response(parseGitDiffResponse) }, "GET /api/git/file-diff": { request: parseGitFileDiffRequest, response: response(parseGitFileDiffResponse) }, "POST /api/git/revert": { request: parseGitFileDiffRequest, response: response(parseGitSuccessResponse) }, "POST /api/git/pull": { request: parseGitPullRequest, response: response(parseGitPullResponse) }, "POST /api/git/push": { request: parseGitPushRequest, response: response(parseGitPushResponse) }, "POST /api/git/fetch": { request: parseGitFetchRequest, response: response(parseGitSuccessResponse) }, "GET /api/git/remotes": { request: parseGitDirectoryQuery, response: response(parseGitRemotesResponse) }, "DELETE /api/git/remotes": { request: parseGitRemoveRemoteRequest, response: response(parseGitSuccessResponse) },
  "POST /api/git/rebase": { request: parseGitRebaseRequest, response: response(parseGitOperationResponse) }, "POST /api/git/rebase/abort": { request: parseGitEmptyRequest, response: response(parseGitOperationResponse) }, "POST /api/git/merge": { request: parseGitMergeRequest, response: response(parseGitOperationResponse) }, "POST /api/git/merge/abort": { request: parseGitEmptyRequest, response: response(parseGitOperationResponse) }, "POST /api/git/rebase/continue": { request: parseGitEmptyRequest, response: response(parseGitOperationResponse) }, "POST /api/git/merge/continue": { request: parseGitEmptyRequest, response: response(parseGitOperationResponse) }, "GET /api/git/conflict-details": { request: parseGitDirectoryQuery, response: response(parseGitConflictDetails) }, "POST /api/git/stash": { request: parseGitStashRequest, response: response(parseGitSuccessResponse) }, "POST /api/git/stash/pop": { request: parseGitEmptyRequest, response: response(parseGitSuccessResponse) }, "POST /api/git/commit": { request: parseGitCommitRequest, response: response(parseGitCommitResponse) },
  "GET /api/git/branches": { request: parseGitDirectoryQuery, response: response(parseGitBranchResponse) }, "POST /api/git/branches": { request: parseGitCreateBranchRequest, response: response(parseGitBranchMutationResponse) }, "DELETE /api/git/branches": { request: parseGitDeleteBranchRequest, response: response(parseGitSuccessResponse) }, "PUT /api/git/branches/rename": { request: parseGitRenameBranchRequest, response: response(parseGitBranchMutationResponse) }, "DELETE /api/git/remote-branches": { request: parseGitDeleteRemoteBranchRequest, response: response(parseGitSuccessResponse) }, "POST /api/git/checkout": { request: parseGitCheckoutBranchRequest, response: response(parseGitBranchMutationResponse) },
  "GET /api/git/worktrees": { request: parseGitDirectoryQuery, response: response(parseGitWorktreesResponse) }, "POST /api/git/worktrees/validate": { request: parseGitWorktreeCreateRequest, response: response(parseGitWorktreeValidationResult) }, "POST /api/git/worktrees": { request: parseGitWorktreeCreateRequest, response: response(parseGitWorktreeCreateResponse) }, "POST /api/git/worktrees/preview": { request: parseGitWorktreeCreateRequest, response: response(parseGitWorktreeCreateResponse) }, "GET /api/git/worktrees/bootstrap-status": { request: parseGitDirectoryQuery, response: response(parseGitWorktreeBootstrapStatus) }, "DELETE /api/git/worktrees": { request: parseGitWorktreeRemoveRequest, response: response(parseGitSuccessResponse) }, "GET /api/git/worktree-type": { request: parseGitDirectoryQuery, response: response(parseGitLinkedWorktreeResponse) }, "POST /api/git/validate-directory": { request: parseGitWorktreeDirectoryRequest, response: response(parseGitWorktreeDirectoryResult) }, "POST /api/git/canonicalize-worktree-state": { request: parseGitCanonicalizeWorktreeRequest, response: response(parseGitCanonicalizeWorktreeResponse) }, "GET /api/git/log": { request: parseGitLogQuery, response: response(parseGitLogResponse) }, "GET /api/git/commit-files": { request: parseGitCommitFilesQuery, response: response(parseGitCommitFilesResponse) },
};
