export type RouteClassification = "contracted" | "sdk-pass-through" | "static-pass-through";
export interface RouteInventoryEntry { registrar: string; classification: RouteClassification; owner: string; consumer?: string; tests?: string; endpoints: readonly string[]; }
const routes = (registrar: string, owner: string, endpoints: readonly string[], classification: RouteClassification = "contracted", consumer?: string, tests?: string): RouteInventoryEntry => ({ registrar, owner, endpoints, classification, consumer, tests });

/** Explicit network ownership. Entries are method/path pairs so the test rejects an un-inventoried route addition. */
export const ROUTE_INVENTORY: readonly RouteInventoryEntry[] = [
  routes("domains/routes/core-routes.ts", "system, ui-auth", ["get /health", "post /api/system/shutdown", "get /api/system/info", "get /auth/session", "post /auth/session", "get /auth/passkey/status", "post /auth/passkey/authenticate/options", "post /auth/passkey/authenticate/verify", "post /auth/passkey/register/options", "post /auth/passkey/register/verify", "get /api/passkeys", "delete /api/passkeys/:id", "post /api/auth/reset"], "contracted", undefined, "core-routes.test.ts"),
  routes("domains/routes/openchamber-routes.ts", "system", ["get /api/openchamber/update-check", "post /api/openchamber/update-install", "get /api/openchamber/models-metadata", "get /api/zen/models"], "contracted", "useUpdateStore, useProviderConfigStore, NotificationSettings", "openchamber-routes.test.ts"),
  routes("domains/routes/pwa-manifest.ts", "static-pass-through", ["get /manifest.webmanifest"], "static-pass-through"),
  routes("domains/notifications/routes.ts", "notifications", ["get /api/push/vapid-public-key", "post /api/push/subscribe", "delete /api/push/subscribe", "post /api/push/visibility", "get /api/push/visibility", "get /api/notifications/stream", "get /api/session-activity", "get /api/sessions/snapshot", "get /api/sessions/status", "get /api/sessions/:id/status", "get /api/sessions/attention", "get /api/sessions/:id/attention", "post /api/sessions/:id/view", "post /api/sessions/:id/unview", "post /api/sessions/:id/message-sent", "post /api/notifications/auto-accept"]),
  routes("domains/server-utils/proxy.ts", "opencode", ["get /api/session", "get /api/global/event", "get /api/event"], "sdk-pass-through"),
  routes("domains/quota/routes.ts", "quota", ["get /api/quota/providers", "get /api/quota/:providerId"]),
  routes("domains/magic-prompts/routes.ts", "opencode", ["get /api/magic-prompts", "put /api/magic-prompts/:id", "delete /api/magic-prompts/:id", "delete /api/magic-prompts"]),
  routes("domains/session-folders/routes.ts", "opencode", ["get /api/session-folders", "post /api/session-folders"]),
  routes("domains/fs/routes.ts", "files", ["get /api/fs/home", "post /api/fs/mkdir", "get /api/fs/stat", "get /api/fs/read", "get /api/fs/raw", "post /api/fs/write", "post /api/fs/delete", "post /api/fs/rename", "post /api/fs/exec", "get /api/fs/exec/:jobId", "get /api/fs/list"]),
  routes("domains/github/routes.ts", "github", ["get /api/github/auth/status", "post /api/github/auth/start", "post /api/github/auth/complete", "post /api/github/auth/activate", "delete /api/github/auth", "get /api/github/me", "get /api/github/pr/status", "post /api/github/pr/create", "post /api/github/pr/update", "post /api/github/pr/merge", "post /api/github/pr/ready", "get /api/github/issues/list", "get /api/github/issues/get", "get /api/github/issues/comments", "get /api/github/pulls/list", "get /api/github/pulls/context"]),
  routes("domains/terminal/routes.ts", "terminal", ["post /api/terminal/create", "get /api/terminal/:sessionId/stream", "post /api/terminal/:sessionId/input", "post /api/terminal/:sessionId/resize", "delete /api/terminal/:sessionId", "post /api/terminal/:sessionId/restart", "post /api/terminal/force-kill"]),
  routes("domains/terminal/ws-server.ts", "terminal", ["get /api/terminal/ws"], "contracted", "terminalApi", "ws-upgrades.test.ts"),
  routes("domains/opencode/routes/core-routes.ts", "themes, ui-auth", ["get /connect", "get /api/config/themes", "post /api/config/reload"], "contracted", "ThemeSystemContext", "core-routes.test.ts, ThemeSystemContext.contract.test.tsx"),
  routes("domains/opencode/routes/routes.ts", "opencode", ["get /api/config/settings", "get /api/config/opencode-resolution", "put /api/config/settings", "post /api/mcp/auth/pending", "get /api/mcp/auth/pending", "delete /api/mcp/auth/pending", "get /api/provider/:providerId/source", "delete /api/provider/:providerId/auth", "post /api/opencode/directory"]),
  routes("domains/opencode/routes/config-entity-routes.ts", "opencode", ["get /api/config/agents/:name", "get /api/config/agents/:name/config", "post /api/config/agents/:name", "patch /api/config/agents/:name", "delete /api/config/agents/:name", "get /api/config/mcp", "get /api/config/mcp/:name", "post /api/config/mcp/:name", "patch /api/config/mcp/:name", "delete /api/config/mcp/:name", "get /api/config/commands/:name", "post /api/config/commands/:name", "patch /api/config/commands/:name", "delete /api/config/commands/:name"], "sdk-pass-through"),
  routes("domains/opencode/routes/project-icon-routes.ts", "project-assets", ["get /api/projects/:projectId/icon", "put /api/projects/:projectId/icon", "delete /api/projects/:projectId/icon", "post /api/projects/:projectId/icon/discover"], "contracted", "useProjectsStore", "project-icon-routes.test.ts"),
  routes("domains/opencode/routes/skill-routes.ts", "skills-catalog", ["get /api/config/skills", "get /api/config/skills/catalog", "get /api/config/skills/catalog/source", "post /api/config/skills/scan", "post /api/config/skills/install", "get /api/config/skills/:name", "get /api/config/skills/:name/files/*filePath", "post /api/config/skills/:name", "patch /api/config/skills/:name", "put /api/config/skills/:name/files/*filePath", "delete /api/config/skills/:name/files/*filePath", "delete /api/config/skills/:name"]),
  routes("domains/git/routes.ts", "git", ["get /api/git/identities", "post /api/git/identities", "put /api/git/identities/:id", "delete /api/git/identities/:id", "get /api/git/global-identity", "get /api/git/discover-credentials", "get /api/git/check", "post /api/git/check-batch", "get /api/git/remote-url", "get /api/git/current-identity", "get /api/git/has-local-identity", "post /api/git/set-identity", "get /api/git/status", "get /api/git/diff", "get /api/git/file-diff", "post /api/git/revert", "post /api/git/pull", "post /api/git/push", "post /api/git/fetch", "get /api/git/remotes", "delete /api/git/remotes", "post /api/git/rebase", "post /api/git/rebase/abort", "post /api/git/merge", "post /api/git/merge/abort", "post /api/git/rebase/continue", "post /api/git/merge/continue", "get /api/git/conflict-details", "post /api/git/stash", "post /api/git/stash/pop", "post /api/git/commit", "get /api/git/branches", "post /api/git/branches", "delete /api/git/branches", "put /api/git/branches/rename", "delete /api/git/remote-branches", "post /api/git/checkout", "get /api/git/worktrees", "post /api/git/worktrees/validate", "post /api/git/worktrees", "post /api/git/worktrees/preview", "get /api/git/worktrees/bootstrap-status", "delete /api/git/worktrees", "get /api/git/worktree-type", "post /api/git/validate-directory", "post /api/git/canonicalize-worktree-state", "get /api/git/log", "get /api/git/commit-files"]),
  routes("domains/event-stream", "event-stream", ["get /api/event/ws", "get /api/global/event/ws"], "contracted", "event-pipeline", "protocol.test.ts, ws-upgrades.test.ts"),
  routes("domains/routes/static-routes.ts", "static-pass-through", [], "static-pass-through"),
] as const;
