import { parseJsonObject, type ParseResult } from "./common.js";

/** Runtime-neutral transport contract for installed skills and catalog providers. */
export const SKILLS_ERROR_CODES = [
  "skills_invalid_request", "skills_invalid_name", "skills_invalid_path", "skills_not_found",
  "skills_conflict", "skills_auth_required", "skills_provider_error", "skills_internal_error",
] as const;
export type SkillsErrorCode = (typeof SKILLS_ERROR_CODES)[number];
export type SkillsError = { code?: SkillsErrorCode; kind?: "authRequired" | "invalidSource" | "gitUnavailable" | "networkError" | "unknown" | "conflicts"; message: string; identities?: SkillsIdentity[]; conflicts?: SkillsConflict[] };
export type SkillsFailure = { ok: false; error: SkillsError };
export type SkillScope = "user" | "project";
export type SkillSource = "opencode" | "claude" | "agents";
export type SkillsIdentity = { id: string; name: string };
export type SkillsConflict = { skillName: string; scope: SkillScope; source?: "opencode" | "agents" };
export type SupportingFile = { name: string; path: string; fullPath: string };
export type SkillSources = { md: { exists: boolean; path: string | null; dir: string | null; fields: string[]; scope?: SkillScope | null; source?: SkillSource | null; supportingFiles: SupportingFile[]; name?: string; description?: string; instructions?: string }; projectMd?: { exists: boolean; path: string | null }; claudeMd?: { exists: boolean; path: string | null }; userMd?: { exists: boolean; path: string | null } };
export type InstalledSkill = { name: string; path: string; scope: SkillScope; source: SkillSource; description?: string; sources?: Partial<SkillSources> };
export type SkillsListResponse = { skills: InstalledSkill[] };
export type SkillDetailResponse = { name: string; sources: SkillSources; scope?: SkillScope | null; source?: SkillSource | null };
export type SkillMutationResponse = { success: true; requiresReload?: boolean; message?: string; reloadDelayMs?: number };
export type SkillsSupportingFileResponse = { path: string; content: string };
export type SkillNameRequest = { name: string };
export type SkillSupportingFileRequest = { name: string; filePath: string; content?: string };
export type SkillConfigRequest = { name?: string; description?: string; instructions?: string; scope?: SkillScope; source?: SkillSource; supportingFiles?: Array<{ path: string; content: string }> };
export type SkillsCatalogSource = { id: string; label: string; description?: string; source: string; defaultSubpath?: string; sourceType?: "github" | "clawdhub" };
export type SkillsCatalogItem = { sourceId: string; repoSource: string; repoSubpath?: string | null; gitIdentityId?: string; skillDir: string; skillName: string; frontmatterName?: string; description?: string; installable: boolean; warnings?: string[]; installed?: { isInstalled: boolean; scope?: SkillScope; source?: SkillSource }; clawdhub?: { slug: string; version: string; displayName?: string; owner?: string; downloads?: number; stars?: number; versionsCount?: number; createdAt?: string | number; updatedAt?: string | number } };
export type SkillsCatalogResponse = { ok: boolean; sources?: SkillsCatalogSource[]; itemsBySource?: Record<string, SkillsCatalogItem[]>; pageInfoBySource?: Record<string, { nextCursor?: string | null }>; error?: SkillsError };
export type SkillsCatalogSourceResponse = { ok: boolean; items?: SkillsCatalogItem[]; nextCursor?: string | null; error?: SkillsError };
export type SkillsRepoScanRequest = { source: string; subpath?: string; gitIdentityId?: string };
export type SkillsRepoScanResponse = { ok: boolean; items?: SkillsCatalogItem[]; error?: SkillsError };
export type SkillsInstallSelection = { skillDir: string; clawdhub?: { slug: string; version: string } };
export type SkillsInstallRequest = { source: string; subpath?: string; gitIdentityId?: string; scope: SkillScope; targetSource?: "opencode" | "agents"; selections: SkillsInstallSelection[]; conflictPolicy?: "prompt" | "skipAll" | "overwriteAll"; conflictDecisions?: Record<string, "skip" | "overwrite"> };
export type SkillsInstallResponse = { ok: boolean; installed?: Array<{ skillName: string; scope: SkillScope; source?: SkillSource }>; skipped?: Array<{ skillName: string; reason: string }>; error?: SkillsError; requiresReload?: boolean; message?: string; reloadDelayMs?: number };

const invalid = <T = never>(error: string): ParseResult<T> => ({ ok: false, error });
const object = (value: unknown) => { const parsed = parseJsonObject(value); return parsed.ok ? parsed.value : null; };
const string = (value: unknown): value is string => typeof value === "string";
const nonEmpty = (value: unknown): value is string => string(value) && value.trim().length > 0;
const optionalString = (value: unknown) => value === undefined || string(value);
const nullableString = (value: unknown) => value === null || string(value);
const scope = (value: unknown): value is SkillScope => value === "user" || value === "project";
const source = (value: unknown): value is SkillSource => value === "opencode" || value === "claude" || value === "agents";
const skillName = (value: unknown): value is string => nonEmpty(value) && /^[a-z0-9][a-z0-9-]*[a-z0-9]$|^[a-z0-9]$/.test(value) && value.length <= 64;
const safeRelativePath = (value: unknown): value is string => nonEmpty(value) && !value.startsWith("/") && !value.includes("\\") && value.split("/").every((part) => part !== "" && part !== "." && part !== "..");
const error = (value: unknown): value is SkillsError => { const input = object(value); return !!input && typeof input.code === "string" && (SKILLS_ERROR_CODES as readonly string[]).includes(input.code) && nonEmpty(input.message); };
const failure = (value: unknown): value is SkillsFailure => { const input = object(value); return !!input && input.ok === false && error(input.error); };
const item = (value: unknown): value is SkillsCatalogItem => { const input = object(value); return !!input && ["sourceId", "repoSource", "skillDir", "skillName"].every((key) => nonEmpty(input[key])) && typeof input.installable === "boolean" && (input.repoSubpath === undefined || nullableString(input.repoSubpath)) && (input.description === undefined || nullableString(input.description)) && (input.warnings === undefined || (Array.isArray(input.warnings) && input.warnings.every(string))); };
const installed = (value: unknown): value is { skillName: string; scope: SkillScope; source?: SkillSource } => { const input = object(value); return !!input && nonEmpty(input.skillName) && scope(input.scope) && (input.source === undefined || source(input.source)); };
const skipped = (value: unknown): value is { skillName: string; reason: string } => { const input = object(value); return !!input && nonEmpty(input.skillName) && string(input.reason); };

export function parseSkillsRepoScanRequest(value: unknown): ParseResult<SkillsRepoScanRequest> { const input = object(value); return input && nonEmpty(input.source) && optionalString(input.subpath) && optionalString(input.gitIdentityId) ? { ok: true, value: input as SkillsRepoScanRequest } : invalid("invalid skills scan request"); }
export function parseSkillNameRequest(value: unknown): ParseResult<SkillNameRequest> { const name = typeof value === "string" ? value : object(value)?.name; return skillName(name) ? { ok: true, value: { name } } : invalid("invalid skill name"); }
export function parseSkillSupportingFileRequest(value: unknown): ParseResult<SkillSupportingFileRequest> { const input = object(value); return input && skillName(input.name) && safeRelativePath(input.filePath) && (input.content === undefined || string(input.content)) ? { ok: true, value: input as SkillSupportingFileRequest } : invalid("invalid skill supporting file request"); }
export function parseSkillConfigRequest(value: unknown, requireName = false): ParseResult<SkillConfigRequest> { const input = object(value); const files = input?.supportingFiles; const validFiles = files === undefined || (Array.isArray(files) && files.every((file) => { const entry = object(file); return !!entry && safeRelativePath(entry.path) && string(entry.content); })); return input && (!requireName || skillName(input.name)) && (input.name === undefined || skillName(input.name)) && optionalString(input.description) && optionalString(input.instructions) && (input.scope === undefined || scope(input.scope)) && (input.source === undefined || source(input.source)) && validFiles ? { ok: true, value: input as SkillConfigRequest } : invalid("invalid skill configuration request"); }
export function parseSkillsListResponse(value: unknown): ParseResult<SkillsListResponse> { const input = object(value); const skills = input?.skills; const validSkill = (skill: unknown) => { const entry = object(skill); return !!entry && nonEmpty(entry.name) && nonEmpty(entry.path) && scope(entry.scope) && source(entry.source) && optionalString(entry.description); }; return input && Array.isArray(skills) && skills.every(validSkill) ? { ok: true, value: input as SkillsListResponse } : invalid("invalid skills list response"); }
export function parseSkillsCatalogResponse(value: unknown): ParseResult<SkillsCatalogResponse> { if (failure(value)) return { ok: true, value }; const input = object(value); const sources = input?.sources; const itemsBySource = object(input?.itemsBySource); const pageInfo = object(input?.pageInfoBySource); const validSource = (sourceValue: unknown) => { const entry = object(sourceValue); return !!entry && ["id", "label", "source"].every((key) => nonEmpty(entry[key])) && optionalString(entry.description) && optionalString(entry.defaultSubpath) && (entry.sourceType === undefined || entry.sourceType === "github" || entry.sourceType === "clawdhub"); }; return input && input.ok === true && Array.isArray(sources) && sources.every(validSource) && !!itemsBySource && Object.values(itemsBySource).every((items) => Array.isArray(items) && items.every(item)) && !!pageInfo ? { ok: true, value: input as SkillsCatalogResponse } : invalid("invalid skills catalog response"); }
export function parseSkillsCatalogSourceResponse(value: unknown): ParseResult<SkillsCatalogSourceResponse> { if (failure(value)) return { ok: true, value }; const input = object(value); return input && input.ok === true && Array.isArray(input.items) && input.items.every(item) && (input.nextCursor === undefined || nullableString(input.nextCursor)) ? { ok: true, value: input as SkillsCatalogSourceResponse } : invalid("invalid skills catalog source response"); }
export function parseSkillsInstallRequest(value: unknown): ParseResult<SkillsInstallRequest> { const input = object(value); const selections = input?.selections; const policy = input?.conflictPolicy; const target = input?.targetSource; const decisions = input?.conflictDecisions; const validSelections = Array.isArray(selections) && selections.every((selection) => { const entry = object(selection); return !!entry && nonEmpty(entry.skillDir) && (entry.clawdhub === undefined || !!object(entry.clawdhub) && nonEmpty(object(entry.clawdhub)?.slug) && nonEmpty(object(entry.clawdhub)?.version)); }); const validDecisions = decisions === undefined || (!!object(decisions) && Object.values(object(decisions)!).every((decision) => decision === "skip" || decision === "overwrite")); return input && nonEmpty(input.source) && scope(input.scope) && validSelections && optionalString(input.subpath) && optionalString(input.gitIdentityId) && (target === undefined || target === "opencode" || target === "agents") && (policy === undefined || policy === "prompt" || policy === "skipAll" || policy === "overwriteAll") && validDecisions ? { ok: true, value: input as SkillsInstallRequest } : invalid("invalid skills install request"); }
export function parseSkillsScanResponse(value: unknown): ParseResult<SkillsRepoScanResponse> { if (failure(value)) return { ok: true, value }; const input = object(value); return input && input.ok === true && Array.isArray(input.items) && input.items.every(item) ? { ok: true, value: input as SkillsRepoScanResponse } : invalid("invalid skills scan response"); }
export function parseSkillsInstallResponse(value: unknown): ParseResult<SkillsInstallResponse> { if (failure(value)) return { ok: true, value }; const input = object(value); return input && input.ok === true && Array.isArray(input.installed) && input.installed.every(installed) && Array.isArray(input.skipped) && input.skipped.every(skipped) && (input.requiresReload === undefined || typeof input.requiresReload === "boolean") && optionalString(input.message) && (input.reloadDelayMs === undefined || typeof input.reloadDelayMs === "number") ? { ok: true, value: input as SkillsInstallResponse } : invalid("invalid skills install response"); }
export function parseSkillDetailResponse(value: unknown): ParseResult<SkillDetailResponse> { const input = object(value); const sources = object(input?.sources); const md = object(sources?.md); const valid = input && skillName(input.name) && !!sources && !!md && typeof md.exists === "boolean" && nullableString(md.path) && nullableString(md.dir) && Array.isArray(md.fields) && md.fields.every(string) && Array.isArray(md.supportingFiles) && md.supportingFiles.every((file) => { const entry = object(file); return !!entry && ["name", "path", "fullPath"].every((key) => string(entry[key])); }) && (input.scope === undefined || input.scope === null || scope(input.scope)) && (input.source === undefined || input.source === null || source(input.source)); return valid ? { ok: true, value: input as SkillDetailResponse } : invalid("invalid skill detail response"); }
export function parseSkillMutationResponse(value: unknown): ParseResult<SkillMutationResponse> { const input = object(value); return input && input.success === true && (input.requiresReload === undefined || typeof input.requiresReload === "boolean") && optionalString(input.message) && (input.reloadDelayMs === undefined || typeof input.reloadDelayMs === "number") ? { ok: true, value: input as SkillMutationResponse } : invalid("invalid skill mutation response"); }
export function parseSkillsSupportingFileResponse(value: unknown): ParseResult<SkillsSupportingFileResponse> { const input = object(value); return input && string(input.path) && string(input.content) ? { ok: true, value: input as SkillsSupportingFileResponse } : invalid("invalid skill supporting file response"); }
export const skillsError = (code: SkillsErrorCode, message = "Skills request failed"): SkillsFailure => ({ ok: false, error: { code, message, conflicts: [] } });
